### ISSUE TITLE
swaggercode-gen

### ISSUE THREAD

**Issue by fullscopeenterprises** [PandaDoc/pandadoc-openapi-specification#7]
Trying to convert to PHP using swagger-codegen 3.0.30 using the JSON file and getting the following errors:

[Thread-0] WARN  i.s.parser.util.DeserializationUtils - Error snake-parsing yaml content

**Comment by akutsanov** [comment]
I'm sorry to hear that.
You can try to use the below command to generate a client through swagger-codegen:
```
docker run --rm -v {some_local_folder}:/local swaggerapi/swagger-codegen-cli-v3:3.0.30 generate \
    -i https://raw.githubusercontent.com/PandaDoc/pandadoc-openapi-specification/main/openapi.json \
    -l php \
    -o /local/php-sdk
```
Also, you can use our PHP client, we published it. https://github.com/PandaDoc/pandadoc-api-php-client
